"""
🧠 {BOT_NAME} — {BOT_DESCRIPTION}
AI Assistant (LLM Powered) | Generated by NEXUM
"""
import os, telebot
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()
bot = telebot.TeleBot(os.getenv("BOT_TOKEN"))
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
model = genai.GenerativeModel('gemini-pro')

SYSTEM_PROMPT = "{PERSONA}"

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "مرحباً! أنا مساعدك الذكي المدعوم بـ NEXUM AI. اسألني أي شيء!")

@bot.message_handler(func=lambda message: True)
def ai_reply(message):
    try:
        response = model.generate_content(f"{SYSTEM_PROMPT}\n\nUser: {message.text}")
        bot.reply_to(message, response.text)
    except Exception as e:
        bot.reply_to(message, "عذراً، حدث خطأ أثناء معالجة طلبك.")
        print(f"Error: {e}")

if __name__ == "__main__":
    print("🤖 {BOT_NAME} AI Assistant Online.")
    bot.infinity_polling()
