"""
🤖 {BOT_NAME} — {BOT_DESCRIPTION}
Generated by NEXUM BotBuilder | Admin: {ADMIN_ID}
"""
import os, telebot
from dotenv import load_dotenv
load_dotenv()

bot = telebot.TeleBot(os.getenv("BOT_TOKEN"))
ADMIN_ID = int(os.getenv("ADMIN_ID", "0"))

SYSTEM_INSTRUCTION = """{PERSONA}"""

@bot.message_handler(commands=['start'])
def start(message):
    bot.send_message(message.chat.id, "مرحباً! أنا {BOT_NAME}. كيف أساعدك؟")

@bot.message_handler(func=lambda m: True)
def handle(message):
    bot.reply_to(message, f"تلقيت: {message.text}")

if __name__ == "__main__":
    print("🤖 {BOT_NAME} Online.")
    bot.infinity_polling()
