"""
🎧 {BOT_NAME} — {BOT_DESCRIPTION}
Customer Service Bot | Generated by NEXUM
"""
import os, telebot
from telebot import types
from dotenv import load_dotenv

load_dotenv()
bot = telebot.TeleBot(os.getenv("BOT_TOKEN"))
ADMIN_ID = int(os.getenv("ADMIN_ID", "0"))

@bot.message_handler(commands=['start'])
def start(message):
    markup = types.InlineKeyboardMarkup()
    markup.add(types.InlineKeyboardButton("❓ الأسئلة الشائعة", callback_data="faq"))
    markup.add(types.InlineKeyboardButton("🎫 فتح تذكرة دعم", callback_data="ticket"))
    markup.add(types.InlineKeyboardButton("👨‍💻 التحدث مع موظف", callback_data="talk_human"))
    
    bot.send_message(message.chat.id, "مرحباً! أنا {BOT_NAME}. كيف يمكنني خدمتك اليوم؟", reply_markup=markup)

@bot.callback_query_handler(func=lambda call: True)
def callback_inline(call):
    if call.data == "faq":
        bot.send_message(call.message.chat.id, "إليك قائمة بالأسئلة الشائعة:\n1. كيف أصدر فاتورة؟\n2. ما هي أوقات العمل؟")
    elif call.data == "ticket":
        msg = bot.send_message(call.message.chat.id, "من فضلك اشرح مشكلتك بالتفصيل:")
        bot.register_next_step_handler(msg, process_ticket)

def process_ticket(message):
    bot.send_message(message.chat.id, "تم استلام تذكرتك بنجاح! رقم التذكرة: OS-" + str(message.message_id))
    bot.send_message(ADMIN_ID, f"🔔 تذكرة جديدة من {message.from_user.username}:\n{message.text}")

if __name__ == "__main__":
    print("🤖 {BOT_NAME} CS Bot Online.")
    bot.infinity_polling()
