"""
🛒 {BOT_NAME} — {BOT_DESCRIPTION}
E-commerce & Catalog Bot | Generated by NEXUM
"""
import os, telebot
from telebot import types
from dotenv import load_dotenv

load_dotenv()
bot = telebot.TeleBot(os.getenv("BOT_TOKEN"))

@bot.message_handler(commands=['start'])
def start(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    markup.add("📦 المنتجات", "🛒 السلة", "🧾 طلباتي")
    bot.send_message(message.chat.id, "مرحباً بك في متجر {BOT_NAME}! تصفح منتجاتنا الآن.", reply_markup=markup)

if __name__ == "__main__":
    print("🤖 {BOT_NAME} E-commerce Bot Online.")
    bot.infinity_polling()
