"""
🏠 {BOT_NAME} — {BOT_DESCRIPTION}
Real Estate Specialist Bot | Generated by NEXUM
"""
import os, telebot
from telebot import types
from dotenv import load_dotenv

load_dotenv()
bot = telebot.TeleBot(os.getenv("BOT_TOKEN"))
ADMIN_ID = int(os.getenv("ADMIN_ID", "0"))

@bot.message_handler(commands=['start'])
def start(message):
    markup = types.ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
    btn1 = types.KeyboardButton("🏢 شقق للبيع")
    btn2 = types.KeyboardButton("🏠 فلل للإيجار")
    btn3 = types.KeyboardButton("📍 البحث بالمنطقة")
    btn4 = types.KeyboardButton("📞 اتصل بنا")
    markup.add(btn1, btn2, btn3, btn4)
    bot.send_message(message.chat.id, "مرحباً بك في {BOT_NAME}! أنا مستشارك العقاري الذكي. كيف يمكنني مساعدتك اليوم؟", reply_markup=markup)

@bot.message_handler(func=lambda m: "شقق" in m.text)
def house_sale(message):
    bot.send_message(message.chat.id, "جاري جلب قائمة بأفضل الشقق المتاحة حالياً...")
    # Logic to fetch from database

@bot.message_handler(func=lambda m: "اتصل" in m.text)
def contact(message):
    bot.send_message(message.chat.id, "يمكنك التواصل مع الإدارة مباشرة عبر: {PHONE_NUMBER}")

if __name__ == "__main__":
    print("🤖 {BOT_NAME} Real Estate Bot Online.")
    bot.infinity_polling()
