"""
📅 {BOT_NAME} — {BOT_DESCRIPTION}
Scheduler & Reminder Bot | Generated by NEXUM
"""
import os, telebot
from dotenv import load_dotenv

load_dotenv()
bot = telebot.TeleBot(os.getenv("BOT_TOKEN"))

@bot.message_handler(commands=['start'])
def start(message):
    bot.send_message(message.chat.id, "مرحباً! أنا {BOT_NAME}. أرسل لي موعداً لأذكرك به.")

if __name__ == "__main__":
    print("🤖 {BOT_NAME} Scheduler Bot Online.")
    bot.infinity_polling()
