"""
🤖 BotFleet — إدارة أسطول البوتات الفرعية
===========================================
تشغيل، إيقاف، سرد، وتحديث بوتات Telegram فرعية.
"""
import os
import sys
import json
import subprocess
import threading
import time
import logging
from typing import List, Dict, Optional
from datetime import datetime

logger = logging.getLogger("nexum.bot_fleet")

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOTS_DIR = os.path.join(BASE_DIR, "registry", "bots")
os.makedirs(BOTS_DIR, exist_ok=True)


class BotFleet:
    """
    إدارة أسطول البوتات الفرعية (تشغيل، إيقاف، سرد، تحديث)
    """
    def __init__(self, storage_path: str):
        self.storage_path = storage_path
        self.bots_dir = BOTS_DIR
        self._running_threads: Dict[str, threading.Thread] = {}
        self._running_bots: Dict[str, dict] = {}
        self._registry = self._load_registry()

    # ═══════════════════════════════════════
    # التخزين
    # ═══════════════════════════════════════

    def _load_registry(self) -> dict:
        if os.path.exists(self.storage_path):
            try:
                with open(self.storage_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    if isinstance(data, dict) and "bots" in data:
                        return data
                    # توافق مع التنسيق القديم
                    return {"bots": data if isinstance(data, dict) else {}}
            except (json.JSONDecodeError, IOError):
                pass
        return {"bots": {}}

    def _save_registry(self):
        os.makedirs(os.path.dirname(self.storage_path), exist_ok=True)
        with open(self.storage_path, 'w', encoding='utf-8') as f:
            # حفظ بدون tokens كاملة
            safe_registry = {"bots": {}}
            for name, info in self._registry.get("bots", {}).items():
                safe_info = dict(info)
                if "token" in safe_info:
                    safe_info["token_hint"] = safe_info["token"][:10] + "***"
                    del safe_info["token"]
                safe_registry["bots"][name] = safe_info
            json.dump(safe_registry, f, ensure_ascii=False, indent=4)

    # ═══════════════════════════════════════
    # إنشاء بوت جديد (spawn)
    # ═══════════════════════════════════════

    def spawn_bot(
        self,
        name: str,
        token: str,
        personality: str = "مساعد ذكي",
        capabilities: list = None,
        admin_id: int = 0
    ) -> dict:
        """إنشاء وتشغيل بوت فرعي جديد"""
        try:
            safe_name = name.replace(" ", "_").lower()
            capabilities = capabilities or ["chat"]

            # تسجيل في الـ registry
            bot_info = {
                "name": safe_name,
                "token": token,
                "personality": personality,
                "capabilities": capabilities,
                "admin_id": admin_id,
                "status": "CREATED",
                "created_at": datetime.utcnow().isoformat(),
                "pid": None,
            }

            self._registry.setdefault("bots", {})[safe_name] = bot_info

            # توليد ملف البوت
            bot_file = self._generate_bot_file(safe_name, bot_info)

            # تشغيل البوت في thread منفصل
            self._start_bot_thread(safe_name, bot_file)

            bot_info["status"] = "RUNNING"
            bot_info["path"] = bot_file
            self._save_registry()

            logger.info(f"Bot spawned: {safe_name}")
            return {
                "status": "success",
                "name": safe_name,
                "path": bot_file,
                "capabilities": capabilities,
            }

        except Exception as e:
            logger.error(f"Spawn failed: {e}")
            return {"status": "error", "error": str(e)}

    def _generate_bot_file(self, name: str, info: dict) -> str:
        """توليد ملف Python للبوت الفرعي"""
        bot_dir = os.path.join(self.bots_dir, name)
        os.makedirs(bot_dir, exist_ok=True)
        bot_file = os.path.join(bot_dir, "bot.py")

        personality = info.get("personality", "مساعد ذكي")
        capabilities = info.get("capabilities", ["chat"])

        code = f'''# -*- coding: utf-8 -*-
"""
🤖 {name} — Generated by NEXUM BotFleet
"""
import os
import sys
import telebot

TOKEN = os.getenv("{name.upper()}_TOKEN", "")
ADMIN_ID = int(os.getenv("{name.upper()}_ADMIN", "0"))

bot = telebot.TeleBot(TOKEN)

PERSONALITY = """{personality}"""
CAPABILITIES = {capabilities}

@bot.message_handler(commands=["start"])
def start(message):
    bot.reply_to(message, "👋 مرحباً! أنا بوت {{name}} — جاهز لمساعدتك.")

@bot.message_handler(content_types=["text"])
def handle_text(message):
    if "chat" in CAPABILITIES:
        try:
            sys.path.insert(0, "{BASE_DIR}")
            from services.gemini_service import gemini_service
            res, _ = gemini_service.ask(
                message.text,
                system_instruction=PERSONALITY
            )
            bot.reply_to(message, res)
        except Exception as e:
            bot.reply_to(message, f"❌ {{e}}")
    else:
        bot.reply_to(message, "لا أملك صلاحية المحادثة.")

if __name__ == "__main__":
    print(f"🤖 {{name}} bot starting...")
    bot.infinity_polling(timeout=30)
'''

        with open(bot_file, "w", encoding="utf-8") as f:
            f.write(code)

        return bot_file

    def _start_bot_thread(self, name: str, bot_file: str):
        """تشغيل البوت في subprocess"""
        def run_bot():
            try:
                process = subprocess.Popen(
                    [sys.executable, bot_file],
                    cwd=os.path.dirname(bot_file),
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                )
                self._running_bots[name] = {
                    "process": process,
                    "pid": process.pid,
                    "started_at": datetime.utcnow().isoformat(),
                }
                # تحديث PID في الـ registry
                if name in self._registry.get("bots", {}):
                    self._registry["bots"][name]["pid"] = process.pid
                    self._registry["bots"][name]["status"] = "RUNNING"
                    self._save_registry()

                process.wait()  # انتظار حتى ينتهي

                # عند الانتهاء
                if name in self._registry.get("bots", {}):
                    self._registry["bots"][name]["status"] = "STOPPED"
                    self._registry["bots"][name]["pid"] = None
                    self._save_registry()

            except Exception as e:
                logger.error(f"Bot thread error ({name}): {e}")

        thread = threading.Thread(target=run_bot, daemon=True, name=f"bot_{name}")
        thread.start()
        self._running_threads[name] = thread

    # ═══════════════════════════════════════
    # إيقاف بوت
    # ═══════════════════════════════════════

    def kill_bot(self, name: str) -> dict:
        """إيقاف بوت فرعي"""
        try:
            bot_data = self._running_bots.get(name)
            if bot_data and bot_data.get("process"):
                bot_data["process"].terminate()
                bot_data["process"].wait(timeout=5)
                del self._running_bots[name]

            if name in self._registry.get("bots", {}):
                self._registry["bots"][name]["status"] = "STOPPED"
                self._registry["bots"][name]["pid"] = None
                self._save_registry()

            logger.info(f"Bot killed: {name}")
            return {"status": "success", "name": name}
        except Exception as e:
            logger.error(f"Kill failed: {e}")
            return {"status": "error", "error": str(e)}

    # ═══════════════════════════════════════
    # إعادة تشغيل بوت
    # ═══════════════════════════════════════

    def restart_bot(self, name: str) -> dict:
        """إعادة تشغيل بوت"""
        self.kill_bot(name)
        time.sleep(1)

        bot_info = self._registry.get("bots", {}).get(name)
        if not bot_info:
            return {"status": "error", "error": f"بوت '{name}' غير موجود في السجل"}

        bot_file = os.path.join(self.bots_dir, name, "bot.py")
        if not os.path.exists(bot_file):
            return {"status": "error", "error": f"ملف البوت غير موجود: {bot_file}"}

        self._start_bot_thread(name, bot_file)
        logger.info(f"Bot restarted: {name}")
        return {"status": "success", "name": name, "action": "restarted"}

    # ═══════════════════════════════════════
    # سرد البوتات
    # ═══════════════════════════════════════

    def list_bots(self) -> List[Dict]:
        """سرد جميع البوتات المسجلة وحالتها"""
        self._registry = self._load_registry()
        bots = self._registry.get("bots", {})

        result = []
        for name, info in bots.items():
            # تحديث الحالة بناءً على PID
            pid = info.get("pid")
            if info.get("status") == "RUNNING" and pid:
                if not self._is_pid_running(pid):
                    info["status"] = "STOPPED"
                    info["pid"] = None

            result.append({
                "name": info.get("name", name),
                "status": info.get("status", "UNKNOWN"),
                "capabilities": info.get("capabilities", []),
                "created_at": info.get("created_at", ""),
                "pid": info.get("pid"),
            })

        self._save_registry()
        return result

    # ═══════════════════════════════════════
    # أدوات مساعدة
    # ═══════════════════════════════════════

    def _is_pid_running(self, pid: int) -> bool:
        if os.name == 'nt':
            try:
                out = subprocess.check_output(
                    f'tasklist /FI "PID eq {pid}"', shell=True
                ).decode()
                return str(pid) in out
            except Exception:
                return False
        else:
            try:
                os.kill(pid, 0)
                return True
            except OSError:
                return False

    def get_bot_info(self, name: str) -> Optional[dict]:
        """معلومات بوت محدد"""
        return self._registry.get("bots", {}).get(name)


# Singleton
bot_fleet = BotFleet(os.path.join(BASE_DIR, 'storage', 'bots.json'))
