package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"sync"
	"time"
)

// Agent represents an autonomous worker in the swarm
type Agent struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

// Proposal represents the solution generated by an individual agent
type Proposal struct {
	AgentID   string  `json:"agent_id"`
	Solution  string  `json:"solution"`
	RiskScore float64 `json:"risk_score"` // 0.0 (Safe) to 1.0 (Critical)
}

// Decision represents the final output approved by the Council of Sages
type Decision struct {
	ApprovedProposal Proposal `json:"approved_proposal"`
	ConsensusReached bool     `json:"consensus_reached"`
	SystemMetrics    string   `json:"system_metrics"`
}

// CouncilOfSages coordinates consensus over proposals
type CouncilOfSages struct {
	ThresholdRisk float64
}

// Evaluate analyzes proposals and returns the safest, highly-optimized option
func (c *CouncilOfSages) Evaluate(proposals []Proposal) (Decision, error) {
	if len(proposals) == 0 {
		return Decision{}, fmt.Errorf("no proposals submitted for evaluation")
	}

	var bestProposal Proposal
	found := false
	minRisk := 1.0

	// Select the proposal with the lowest risk score below the threshold
	for _, prop := range proposals {
		if prop.RiskScore <= c.ThresholdRisk && prop.RiskScore < minRisk {
			minRisk = prop.RiskScore
			bestProposal = prop
			found = true
		}
	}

	if !found {
		return Decision{
			ConsensusReached: false,
			SystemMetrics:    "All proposals rejected due to high security risk profiles.",
		}, nil
	}

	return Decision{
		ApprovedProposal: bestProposal,
		ConsensusReached: true,
		SystemMetrics:    fmt.Sprintf("Consensus reached on Agent [%s] proposal. Risk level: %.2f", bestProposal.AgentID, bestProposal.RiskScore),
	}, nil
}

// ExecuteTask parallelizes agent operations and pipes them to the Council
func ExecuteTask(ctx context.Context, agents []Agent, task string, council *CouncilOfSages) (Decision, error) {
	proposalChan := make(chan Proposal, len(agents))
	var wg sync.WaitGroup

	for _, agent := range agents {
		wg.Add(1)
		go func(a Agent) {
			defer wg.Done()

			// Simulate sub-agent analytical processing time
			select {
			case <-time.After(100 * time.Millisecond):
				// Mocking specialized agent output logic
				risk := 0.1
				if a.ID == "Agent-Security-QA" {
					risk = 0.05 // Safest proposal
				} else if a.ID == "Agent-Rapid-Dev" {
					risk = 0.45 // Fast but riskier
				}

				proposalChan <- Proposal{
					AgentID:   a.ID,
					Solution:  fmt.Sprintf("[%s] processed task: '%s' with custom optimization matrix.", a.Role, task),
					RiskScore: risk,
				}
			case <-ctx.Done():
				return
			}
		}(agent)
	}

	wg.Wait()
	close(proposalChan)

	var proposals []Proposal
	for prop := range proposalChan {
		proposals = append(proposals, prop)
	}

	// Evaluate consensus via the Council of Sages
	return council.Evaluate(proposals)
}

func main() {
	// Parse CLI Flags
	taskPtr := flag.String("task", "Integrate Google Agent Platform with consensus mechanisms", "The task to analyze")
	thresholdPtr := flag.Float64("threshold", 0.3, "The maximum acceptable risk threshold")
	flag.Parse()

	agents := []Agent{
		{ID: "Agent-Arch", Role: "Software Architect"},
		{ID: "Agent-Rapid-Dev", Role: "Rapid Developer"},
		{ID: "Agent-Security-QA", Role: "Security & QA Auditor"},
	}

	council := &CouncilOfSages{ThresholdRisk: *thresholdPtr}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	decision, err := ExecuteTask(ctx, agents, *taskPtr, council)
	if err != nil {
		// Output error as JSON for consistent parsing
		errMap := map[string]string{"error": err.Error()}
		errJSON, _ := json.Marshal(errMap)
		fmt.Println(string(errJSON))
		return
	}

	// Output clean JSON to stdout
	output, err := json.MarshalIndent(decision, "", "  ")
	if err != nil {
		errMap := map[string]string{"error": fmt.Sprintf("Error marshaling JSON: %v", err)}
		errJSON, _ := json.Marshal(errMap)
		fmt.Println(string(errJSON))
		return
	}

	fmt.Println(string(output))
}
